name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build binaries
      run: |
        # Build for Linux
        GOOS=linux GOARCH=amd64 go build -o gosh-linux-amd64 .
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -o gosh-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o gosh-darwin-arm64 .
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -o gosh-windows-amd64.exe .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          gosh-linux-amd64
          gosh-darwin-amd64
          gosh-darwin-arm64
          gosh-windows-amd64.exe
        draft: false
        prerelease: false
        generate_release_notes: true
